# Generated by Django 5.0.6 on 2024-06-14 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partitura',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
